# Generated by Django 5.2.2 on 2025-06-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('joined_date', models.DateField()),
                ('subject', models.CharField(choices=[('MAL', ' Malayalam'), ('ENG', 'english'), ('MAT', 'Maths'), ('SCI', 'Science')], max_length=3)),
                ('experience', models.IntegerField()),
            ],
        ),
    ]
