# Generated by Django 5.2.2 on 2025-06-12 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_teacherdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherDetail',
        ),
    ]
