# Generated by Django 5.2.2 on 2025-06-12 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_delete_teacherdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='roll_number',
            new_name='roll_no',
        ),
    ]
