# Generated by Django 5.2.2 on 2025-06-14 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_rename_roll_number_student_roll_no'),
        ('subject', '0003_rename_subject1_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subject.subject'),
        ),
    ]
