# Generated by Django 5.2.2 on 2025-07-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/'),
        ),
    ]
