# Generated by Django 5.2.2 on 2025-06-14 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_subject1_delete_subject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject1',
            new_name='Subject',
        ),
    ]
